# Generated by Django 3.0 on 2024-03-30 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя меню')),
                ('slug', models.SlugField(verbose_name='Url меню')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название раздела')),
                ('slug', models.SlugField(verbose_name='Url раздела')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cool_app.Menu', verbose_name='Меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cool_app.MenuItem', verbose_name='Родитель')),
            ],
        ),
    ]
